# Generated by Django 5.0.2 on 2024-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnapoles', '0003_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='coordenadas',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
